import { Inter } from "next/font/google";
import "./styles/globals.css";
import MainNav from "./components/ui/Main-Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Workout Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-50">
        <MainNav />
        {children}
      </body>
    </html>
  );
}
